// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Anchor struct {
	ID           int64   `json:"id"`
	CreatedAt    string  `json:"created_at"`
	PecIndex     int64   `json:"pec_index"`
	At           string  `json:"at"`
	SigmaS       float64 `json:"sigma_s"`
	Source       string  `json:"source"`
	PeriodS      float64 `json:"period_s"`
	PeriodSigmaS float64 `json:"period_sigma_s"`
	Readings     int64   `json:"readings"`
	Note         string  `json:"note"`
}

type Capture struct {
	ID              int64         `json:"id"`
	CreatedAt       string        `json:"created_at"`
	AnchorID        sql.NullInt64 `json:"anchor_id"`
	FileSha256      string        `json:"file_sha256"`
	SourceName      string        `json:"source_name"`
	StartedAt       string        `json:"started_at"`
	EndedAt         string        `json:"ended_at"`
	TrackFrom       string        `json:"track_from"`
	TrackTo         string        `json:"track_to"`
	Frames          int64         `json:"frames"`
	EncoderReadings int64         `json:"encoder_readings"`
	EncoderRate     float64       `json:"encoder_rate"`
	EncoderRateSig  float64       `json:"encoder_rate_sig"`
	EncoderRms      float64       `json:"encoder_rms"`
	CountsPerTurn   float64       `json:"counts_per_turn"`
	PeriodS         float64       `json:"period_s"`
	PeriodSigmaS    float64       `json:"period_sigma_s"`
	IndexReadings   int64         `json:"index_readings"`
	IndexOffset     float64       `json:"index_offset"`
	IndexSpread     float64       `json:"index_spread"`
	WarningsJson    string        `json:"warnings_json"`
	Notes           string        `json:"notes"`
}

type File struct {
	Sha256     string `json:"sha256"`
	Kind       string `json:"kind"`
	Name       string `json:"name"`
	Size       int64  `json:"size"`
	UploadedAt string `json:"uploaded_at"`
}

type Fit struct {
	ID           int64         `json:"id"`
	CreatedAt    string        `json:"created_at"`
	Mode         string        `json:"mode"`
	RunID        sql.NullInt64 `json:"run_id"`
	AnchorID     sql.NullInt64 `json:"anchor_id"`
	FileSha256   string        `json:"file_sha256"`
	SourceName   string        `json:"source_name"`
	PhaseRef     string        `json:"phase_ref"`
	PeriodS      float64       `json:"period_s"`
	Harmonics    int64         `json:"harmonics"`
	Inverted     int64         `json:"inverted"`
	Amp1Arcsec   float64       `json:"amp1_arcsec"`
	P2pTicks     int64         `json:"p2p_ticks"`
	QuantRms     float64       `json:"quant_rms"`
	PhaseErrDeg  float64       `json:"phase_err_deg"`
	TableText    string        `json:"table_text"`
	MetaJson     string        `json:"meta_json"`
	WarningsJson string        `json:"warnings_json"`
	ToolVersion  string        `json:"tool_version"`
	Notes        string        `json:"notes"`
}

type Run struct {
	ID             int64         `json:"id"`
	CreatedAt      string        `json:"created_at"`
	Kind           string        `json:"kind"`
	FileSha256     string        `json:"file_sha256"`
	SourceName     string        `json:"source_name"`
	SessionIndex   int64         `json:"session_index"`
	SessionBegins  string        `json:"session_begins"`
	Equipment      string        `json:"equipment"`
	RaHours        float64       `json:"ra_hours"`
	DecDeg         float64       `json:"dec_deg"`
	HourAngle      float64       `json:"hour_angle"`
	AltDeg         float64       `json:"alt_deg"`
	PierSide       string        `json:"pier_side"`
	PixelScale     float64       `json:"pixel_scale"`
	ExposureMs     int64         `json:"exposure_ms"`
	SampleCount    int64         `json:"sample_count"`
	CadenceS       float64       `json:"cadence_s"`
	SpanS          float64       `json:"span_s"`
	Cycles         float64       `json:"cycles"`
	DriftArcsecMin float64       `json:"drift_arcsec_min"`
	PeriodS        float64       `json:"period_s"`
	PeriodSigmaS   float64       `json:"period_sigma_s"`
	PeriodFixed    int64         `json:"period_fixed"`
	HarmonicsJson  string        `json:"harmonics_json"`
	Amp1Arcsec     float64       `json:"amp1_arcsec"`
	Phase1Deg      float64       `json:"phase1_deg"`
	PeriodicRms    float64       `json:"periodic_rms"`
	ResidualRms    float64       `json:"residual_rms"`
	PeakToPeak     float64       `json:"peak_to_peak"`
	GuidingActive  int64         `json:"guiding_active"`
	PecOn          sql.NullInt64 `json:"pec_on"`
	RaSign         float64       `json:"ra_sign"`
	OptionsJson    string        `json:"options_json"`
	WarningsJson   string        `json:"warnings_json"`
	ToolVersion    string        `json:"tool_version"`
	Notes          string        `json:"notes"`
}
