// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type File struct {
	Sha256     string `json:"sha256"`
	Kind       string `json:"kind"`
	Name       string `json:"name"`
	Size       int64  `json:"size"`
	UploadedAt string `json:"uploaded_at"`
}

type Run struct {
	ID             int64         `json:"id"`
	CreatedAt      string        `json:"created_at"`
	Kind           string        `json:"kind"`
	FileSha256     string        `json:"file_sha256"`
	SourceName     string        `json:"source_name"`
	SessionIndex   int64         `json:"session_index"`
	SessionBegins  string        `json:"session_begins"`
	Equipment      string        `json:"equipment"`
	RaHours        float64       `json:"ra_hours"`
	DecDeg         float64       `json:"dec_deg"`
	HourAngle      float64       `json:"hour_angle"`
	AltDeg         float64       `json:"alt_deg"`
	PierSide       string        `json:"pier_side"`
	PixelScale     float64       `json:"pixel_scale"`
	ExposureMs     int64         `json:"exposure_ms"`
	SampleCount    int64         `json:"sample_count"`
	CadenceS       float64       `json:"cadence_s"`
	SpanS          float64       `json:"span_s"`
	Cycles         float64       `json:"cycles"`
	DriftArcsecMin float64       `json:"drift_arcsec_min"`
	PeriodS        float64       `json:"period_s"`
	PeriodSigmaS   float64       `json:"period_sigma_s"`
	PeriodFixed    int64         `json:"period_fixed"`
	HarmonicsJson  string        `json:"harmonics_json"`
	Amp1Arcsec     float64       `json:"amp1_arcsec"`
	Phase1Deg      float64       `json:"phase1_deg"`
	PeriodicRms    float64       `json:"periodic_rms"`
	ResidualRms    float64       `json:"residual_rms"`
	PeakToPeak     float64       `json:"peak_to_peak"`
	GuidingActive  int64         `json:"guiding_active"`
	PecOn          sql.NullInt64 `json:"pec_on"`
	RaSign         float64       `json:"ra_sign"`
	OptionsJson    string        `json:"options_json"`
	WarningsJson   string        `json:"warnings_json"`
	ToolVersion    string        `json:"tool_version"`
	Notes          string        `json:"notes"`
}
