// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const deleteAnchor = `-- name: DeleteAnchor :exec
DELETE FROM anchors WHERE id = ?
`

func (q *Queries) DeleteAnchor(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAnchor, id)
	return err
}

const deleteCapture = `-- name: DeleteCapture :exec
DELETE FROM captures WHERE id = ?
`

func (q *Queries) DeleteCapture(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCapture, id)
	return err
}

const deleteFit = `-- name: DeleteFit :exec
DELETE FROM fits WHERE id = ?
`

func (q *Queries) DeleteFit(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFit, id)
	return err
}

const deleteRun = `-- name: DeleteRun :exec
DELETE FROM runs WHERE id = ?
`

func (q *Queries) DeleteRun(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRun, id)
	return err
}

const deleteUnreferencedFile = `-- name: DeleteUnreferencedFile :execresult
DELETE FROM files
WHERE sha256 = ? AND kind = 'phd2live'
  AND NOT EXISTS (SELECT 1 FROM runs r WHERE r.file_sha256 = files.sha256)
  AND NOT EXISTS (SELECT 1 FROM fits x WHERE x.file_sha256 = files.sha256)
`

func (q *Queries) DeleteUnreferencedFile(ctx context.Context, sha256 string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUnreferencedFile, sha256)
}

const getAnchor = `-- name: GetAnchor :one
SELECT id, created_at, pec_index, at, sigma_s, source, period_s, period_sigma_s, readings, note FROM anchors WHERE id = ?
`

func (q *Queries) GetAnchor(ctx context.Context, id int64) (Anchor, error) {
	row := q.db.QueryRowContext(ctx, getAnchor, id)
	var i Anchor
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.PecIndex,
		&i.At,
		&i.SigmaS,
		&i.Source,
		&i.PeriodS,
		&i.PeriodSigmaS,
		&i.Readings,
		&i.Note,
	)
	return i, err
}

const getCapture = `-- name: GetCapture :one
SELECT id, created_at, anchor_id, file_sha256, source_name, started_at, ended_at, track_from, track_to, frames, encoder_readings, encoder_rate, encoder_rate_sig, encoder_rms, counts_per_turn, period_s, period_sigma_s, index_readings, index_offset, index_spread, warnings_json, notes FROM captures WHERE id = ?
`

func (q *Queries) GetCapture(ctx context.Context, id int64) (Capture, error) {
	row := q.db.QueryRowContext(ctx, getCapture, id)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.AnchorID,
		&i.FileSha256,
		&i.SourceName,
		&i.StartedAt,
		&i.EndedAt,
		&i.TrackFrom,
		&i.TrackTo,
		&i.Frames,
		&i.EncoderReadings,
		&i.EncoderRate,
		&i.EncoderRateSig,
		&i.EncoderRms,
		&i.CountsPerTurn,
		&i.PeriodS,
		&i.PeriodSigmaS,
		&i.IndexReadings,
		&i.IndexOffset,
		&i.IndexSpread,
		&i.WarningsJson,
		&i.Notes,
	)
	return i, err
}

const getFile = `-- name: GetFile :one
SELECT sha256, kind, name, size, uploaded_at FROM files WHERE sha256 = ?
`

func (q *Queries) GetFile(ctx context.Context, sha256 string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFile, sha256)
	var i File
	err := row.Scan(
		&i.Sha256,
		&i.Kind,
		&i.Name,
		&i.Size,
		&i.UploadedAt,
	)
	return i, err
}

const getFit = `-- name: GetFit :one
SELECT id, created_at, mode, run_id, anchor_id, file_sha256, source_name, phase_ref, period_s, harmonics, inverted, amp1_arcsec, p2p_ticks, quant_rms, phase_err_deg, table_text, meta_json, warnings_json, tool_version, notes FROM fits WHERE id = ?
`

func (q *Queries) GetFit(ctx context.Context, id int64) (Fit, error) {
	row := q.db.QueryRowContext(ctx, getFit, id)
	var i Fit
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Mode,
		&i.RunID,
		&i.AnchorID,
		&i.FileSha256,
		&i.SourceName,
		&i.PhaseRef,
		&i.PeriodS,
		&i.Harmonics,
		&i.Inverted,
		&i.Amp1Arcsec,
		&i.P2pTicks,
		&i.QuantRms,
		&i.PhaseErrDeg,
		&i.TableText,
		&i.MetaJson,
		&i.WarningsJson,
		&i.ToolVersion,
		&i.Notes,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, created_at, kind, file_sha256, source_name, session_index, session_begins, equipment, ra_hours, dec_deg, hour_angle, alt_deg, pier_side, pixel_scale, exposure_ms, sample_count, cadence_s, span_s, cycles, drift_arcsec_min, period_s, period_sigma_s, period_fixed, harmonics_json, amp1_arcsec, phase1_deg, periodic_rms, residual_rms, peak_to_peak, guiding_active, pec_on, ra_sign, options_json, warnings_json, tool_version, notes FROM runs WHERE id = ?
`

func (q *Queries) GetRun(ctx context.Context, id int64) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Kind,
		&i.FileSha256,
		&i.SourceName,
		&i.SessionIndex,
		&i.SessionBegins,
		&i.Equipment,
		&i.RaHours,
		&i.DecDeg,
		&i.HourAngle,
		&i.AltDeg,
		&i.PierSide,
		&i.PixelScale,
		&i.ExposureMs,
		&i.SampleCount,
		&i.CadenceS,
		&i.SpanS,
		&i.Cycles,
		&i.DriftArcsecMin,
		&i.PeriodS,
		&i.PeriodSigmaS,
		&i.PeriodFixed,
		&i.HarmonicsJson,
		&i.Amp1Arcsec,
		&i.Phase1Deg,
		&i.PeriodicRms,
		&i.ResidualRms,
		&i.PeakToPeak,
		&i.GuidingActive,
		&i.PecOn,
		&i.RaSign,
		&i.OptionsJson,
		&i.WarningsJson,
		&i.ToolVersion,
		&i.Notes,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE key = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const insertAnchor = `-- name: InsertAnchor :execresult
INSERT INTO anchors (created_at, pec_index, at, sigma_s, source, period_s, period_sigma_s, readings, note)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAnchorParams struct {
	CreatedAt    string  `json:"created_at"`
	PecIndex     int64   `json:"pec_index"`
	At           string  `json:"at"`
	SigmaS       float64 `json:"sigma_s"`
	Source       string  `json:"source"`
	PeriodS      float64 `json:"period_s"`
	PeriodSigmaS float64 `json:"period_sigma_s"`
	Readings     int64   `json:"readings"`
	Note         string  `json:"note"`
}

func (q *Queries) InsertAnchor(ctx context.Context, arg InsertAnchorParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertAnchor,
		arg.CreatedAt,
		arg.PecIndex,
		arg.At,
		arg.SigmaS,
		arg.Source,
		arg.PeriodS,
		arg.PeriodSigmaS,
		arg.Readings,
		arg.Note,
	)
}

const insertCapture = `-- name: InsertCapture :execresult
INSERT INTO captures (
    created_at, anchor_id, file_sha256, source_name, started_at, ended_at, track_from, track_to,
    frames, encoder_readings, encoder_rate, encoder_rate_sig, encoder_rms, counts_per_turn,
    period_s, period_sigma_s, index_readings, index_offset, index_spread, warnings_json, notes
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?
)
`

type InsertCaptureParams struct {
	CreatedAt       string        `json:"created_at"`
	AnchorID        sql.NullInt64 `json:"anchor_id"`
	FileSha256      string        `json:"file_sha256"`
	SourceName      string        `json:"source_name"`
	StartedAt       string        `json:"started_at"`
	EndedAt         string        `json:"ended_at"`
	TrackFrom       string        `json:"track_from"`
	TrackTo         string        `json:"track_to"`
	Frames          int64         `json:"frames"`
	EncoderReadings int64         `json:"encoder_readings"`
	EncoderRate     float64       `json:"encoder_rate"`
	EncoderRateSig  float64       `json:"encoder_rate_sig"`
	EncoderRms      float64       `json:"encoder_rms"`
	CountsPerTurn   float64       `json:"counts_per_turn"`
	PeriodS         float64       `json:"period_s"`
	PeriodSigmaS    float64       `json:"period_sigma_s"`
	IndexReadings   int64         `json:"index_readings"`
	IndexOffset     float64       `json:"index_offset"`
	IndexSpread     float64       `json:"index_spread"`
	WarningsJson    string        `json:"warnings_json"`
	Notes           string        `json:"notes"`
}

func (q *Queries) InsertCapture(ctx context.Context, arg InsertCaptureParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertCapture,
		arg.CreatedAt,
		arg.AnchorID,
		arg.FileSha256,
		arg.SourceName,
		arg.StartedAt,
		arg.EndedAt,
		arg.TrackFrom,
		arg.TrackTo,
		arg.Frames,
		arg.EncoderReadings,
		arg.EncoderRate,
		arg.EncoderRateSig,
		arg.EncoderRms,
		arg.CountsPerTurn,
		arg.PeriodS,
		arg.PeriodSigmaS,
		arg.IndexReadings,
		arg.IndexOffset,
		arg.IndexSpread,
		arg.WarningsJson,
		arg.Notes,
	)
}

const insertFit = `-- name: InsertFit :execresult
INSERT INTO fits (
    created_at, mode, run_id, anchor_id, file_sha256, source_name, phase_ref,
    period_s, harmonics, inverted, amp1_arcsec, p2p_ticks, quant_rms, phase_err_deg,
    table_text, meta_json, warnings_json, tool_version, notes
) VALUES (
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?
)
`

type InsertFitParams struct {
	CreatedAt    string        `json:"created_at"`
	Mode         string        `json:"mode"`
	RunID        sql.NullInt64 `json:"run_id"`
	AnchorID     sql.NullInt64 `json:"anchor_id"`
	FileSha256   string        `json:"file_sha256"`
	SourceName   string        `json:"source_name"`
	PhaseRef     string        `json:"phase_ref"`
	PeriodS      float64       `json:"period_s"`
	Harmonics    int64         `json:"harmonics"`
	Inverted     int64         `json:"inverted"`
	Amp1Arcsec   float64       `json:"amp1_arcsec"`
	P2pTicks     int64         `json:"p2p_ticks"`
	QuantRms     float64       `json:"quant_rms"`
	PhaseErrDeg  float64       `json:"phase_err_deg"`
	TableText    string        `json:"table_text"`
	MetaJson     string        `json:"meta_json"`
	WarningsJson string        `json:"warnings_json"`
	ToolVersion  string        `json:"tool_version"`
	Notes        string        `json:"notes"`
}

func (q *Queries) InsertFit(ctx context.Context, arg InsertFitParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertFit,
		arg.CreatedAt,
		arg.Mode,
		arg.RunID,
		arg.AnchorID,
		arg.FileSha256,
		arg.SourceName,
		arg.PhaseRef,
		arg.PeriodS,
		arg.Harmonics,
		arg.Inverted,
		arg.Amp1Arcsec,
		arg.P2pTicks,
		arg.QuantRms,
		arg.PhaseErrDeg,
		arg.TableText,
		arg.MetaJson,
		arg.WarningsJson,
		arg.ToolVersion,
		arg.Notes,
	)
}

const insertRun = `-- name: InsertRun :execresult
INSERT INTO runs (
    created_at, kind, file_sha256, source_name, session_index, session_begins, equipment,
    ra_hours, dec_deg, hour_angle, alt_deg, pier_side, pixel_scale, exposure_ms,
    sample_count, cadence_s, span_s, cycles, drift_arcsec_min,
    period_s, period_sigma_s, period_fixed, harmonics_json, amp1_arcsec, phase1_deg,
    periodic_rms, residual_rms, peak_to_peak, guiding_active, pec_on, ra_sign,
    options_json, warnings_json, tool_version, notes
) VALUES (
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?
)
`

type InsertRunParams struct {
	CreatedAt      string        `json:"created_at"`
	Kind           string        `json:"kind"`
	FileSha256     string        `json:"file_sha256"`
	SourceName     string        `json:"source_name"`
	SessionIndex   int64         `json:"session_index"`
	SessionBegins  string        `json:"session_begins"`
	Equipment      string        `json:"equipment"`
	RaHours        float64       `json:"ra_hours"`
	DecDeg         float64       `json:"dec_deg"`
	HourAngle      float64       `json:"hour_angle"`
	AltDeg         float64       `json:"alt_deg"`
	PierSide       string        `json:"pier_side"`
	PixelScale     float64       `json:"pixel_scale"`
	ExposureMs     int64         `json:"exposure_ms"`
	SampleCount    int64         `json:"sample_count"`
	CadenceS       float64       `json:"cadence_s"`
	SpanS          float64       `json:"span_s"`
	Cycles         float64       `json:"cycles"`
	DriftArcsecMin float64       `json:"drift_arcsec_min"`
	PeriodS        float64       `json:"period_s"`
	PeriodSigmaS   float64       `json:"period_sigma_s"`
	PeriodFixed    int64         `json:"period_fixed"`
	HarmonicsJson  string        `json:"harmonics_json"`
	Amp1Arcsec     float64       `json:"amp1_arcsec"`
	Phase1Deg      float64       `json:"phase1_deg"`
	PeriodicRms    float64       `json:"periodic_rms"`
	ResidualRms    float64       `json:"residual_rms"`
	PeakToPeak     float64       `json:"peak_to_peak"`
	GuidingActive  int64         `json:"guiding_active"`
	PecOn          sql.NullInt64 `json:"pec_on"`
	RaSign         float64       `json:"ra_sign"`
	OptionsJson    string        `json:"options_json"`
	WarningsJson   string        `json:"warnings_json"`
	ToolVersion    string        `json:"tool_version"`
	Notes          string        `json:"notes"`
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertRun,
		arg.CreatedAt,
		arg.Kind,
		arg.FileSha256,
		arg.SourceName,
		arg.SessionIndex,
		arg.SessionBegins,
		arg.Equipment,
		arg.RaHours,
		arg.DecDeg,
		arg.HourAngle,
		arg.AltDeg,
		arg.PierSide,
		arg.PixelScale,
		arg.ExposureMs,
		arg.SampleCount,
		arg.CadenceS,
		arg.SpanS,
		arg.Cycles,
		arg.DriftArcsecMin,
		arg.PeriodS,
		arg.PeriodSigmaS,
		arg.PeriodFixed,
		arg.HarmonicsJson,
		arg.Amp1Arcsec,
		arg.Phase1Deg,
		arg.PeriodicRms,
		arg.ResidualRms,
		arg.PeakToPeak,
		arg.GuidingActive,
		arg.PecOn,
		arg.RaSign,
		arg.OptionsJson,
		arg.WarningsJson,
		arg.ToolVersion,
		arg.Notes,
	)
}

const listAnalyseRuns = `-- name: ListAnalyseRuns :many
SELECT id, created_at, kind, file_sha256, source_name, session_index, session_begins, equipment, ra_hours, dec_deg, hour_angle, alt_deg, pier_side, pixel_scale, exposure_ms, sample_count, cadence_s, span_s, cycles, drift_arcsec_min, period_s, period_sigma_s, period_fixed, harmonics_json, amp1_arcsec, phase1_deg, periodic_rms, residual_rms, peak_to_peak, guiding_active, pec_on, ra_sign, options_json, warnings_json, tool_version, notes FROM runs WHERE kind = 'analyse' ORDER BY created_at DESC, id DESC LIMIT ?
`

func (q *Queries) ListAnalyseRuns(ctx context.Context, limit int64) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listAnalyseRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Kind,
			&i.FileSha256,
			&i.SourceName,
			&i.SessionIndex,
			&i.SessionBegins,
			&i.Equipment,
			&i.RaHours,
			&i.DecDeg,
			&i.HourAngle,
			&i.AltDeg,
			&i.PierSide,
			&i.PixelScale,
			&i.ExposureMs,
			&i.SampleCount,
			&i.CadenceS,
			&i.SpanS,
			&i.Cycles,
			&i.DriftArcsecMin,
			&i.PeriodS,
			&i.PeriodSigmaS,
			&i.PeriodFixed,
			&i.HarmonicsJson,
			&i.Amp1Arcsec,
			&i.Phase1Deg,
			&i.PeriodicRms,
			&i.ResidualRms,
			&i.PeakToPeak,
			&i.GuidingActive,
			&i.PecOn,
			&i.RaSign,
			&i.OptionsJson,
			&i.WarningsJson,
			&i.ToolVersion,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnchors = `-- name: ListAnchors :many
SELECT id, created_at, pec_index, at, sigma_s, source, period_s, period_sigma_s, readings, note FROM anchors ORDER BY at DESC, id DESC LIMIT ?
`

func (q *Queries) ListAnchors(ctx context.Context, limit int64) ([]Anchor, error) {
	rows, err := q.db.QueryContext(ctx, listAnchors, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Anchor{}
	for rows.Next() {
		var i Anchor
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.PecIndex,
			&i.At,
			&i.SigmaS,
			&i.Source,
			&i.PeriodS,
			&i.PeriodSigmaS,
			&i.Readings,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCaptures = `-- name: ListCaptures :many
SELECT id, created_at, anchor_id, file_sha256, source_name, started_at, ended_at, track_from, track_to, frames, encoder_readings, encoder_rate, encoder_rate_sig, encoder_rms, counts_per_turn, period_s, period_sigma_s, index_readings, index_offset, index_spread, warnings_json, notes FROM captures ORDER BY created_at DESC, id DESC LIMIT ?
`

func (q *Queries) ListCaptures(ctx context.Context, limit int64) ([]Capture, error) {
	rows, err := q.db.QueryContext(ctx, listCaptures, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Capture{}
	for rows.Next() {
		var i Capture
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.AnchorID,
			&i.FileSha256,
			&i.SourceName,
			&i.StartedAt,
			&i.EndedAt,
			&i.TrackFrom,
			&i.TrackTo,
			&i.Frames,
			&i.EncoderReadings,
			&i.EncoderRate,
			&i.EncoderRateSig,
			&i.EncoderRms,
			&i.CountsPerTurn,
			&i.PeriodS,
			&i.PeriodSigmaS,
			&i.IndexReadings,
			&i.IndexOffset,
			&i.IndexSpread,
			&i.WarningsJson,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFits = `-- name: ListFits :many
SELECT id, created_at, mode, run_id, anchor_id, file_sha256, source_name, phase_ref, period_s, harmonics, inverted, amp1_arcsec, p2p_ticks, quant_rms, phase_err_deg, table_text, meta_json, warnings_json, tool_version, notes FROM fits ORDER BY created_at DESC, id DESC LIMIT ?
`

func (q *Queries) ListFits(ctx context.Context, limit int64) ([]Fit, error) {
	rows, err := q.db.QueryContext(ctx, listFits, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fit{}
	for rows.Next() {
		var i Fit
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Mode,
			&i.RunID,
			&i.AnchorID,
			&i.FileSha256,
			&i.SourceName,
			&i.PhaseRef,
			&i.PeriodS,
			&i.Harmonics,
			&i.Inverted,
			&i.Amp1Arcsec,
			&i.P2pTicks,
			&i.QuantRms,
			&i.PhaseErrDeg,
			&i.TableText,
			&i.MetaJson,
			&i.WarningsJson,
			&i.ToolVersion,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveFiles = `-- name: ListLiveFiles :many
SELECT f.sha256, f.kind, f.name, f.size, f.uploaded_at, (SELECT COUNT(*) FROM runs r WHERE r.file_sha256 = f.sha256) AS run_count
FROM files f
WHERE f.kind = 'phd2live'
ORDER BY f.uploaded_at DESC, f.sha256
LIMIT ?
`

type ListLiveFilesRow struct {
	Sha256     string `json:"sha256"`
	Kind       string `json:"kind"`
	Name       string `json:"name"`
	Size       int64  `json:"size"`
	UploadedAt string `json:"uploaded_at"`
	RunCount   int64  `json:"run_count"`
}

func (q *Queries) ListLiveFiles(ctx context.Context, limit int64) ([]ListLiveFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLiveFiles, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiveFilesRow{}
	for rows.Next() {
		var i ListLiveFilesRow
		if err := rows.Scan(
			&i.Sha256,
			&i.Kind,
			&i.Name,
			&i.Size,
			&i.UploadedAt,
			&i.RunCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, created_at, kind, file_sha256, source_name, session_index, session_begins, equipment, ra_hours, dec_deg, hour_angle, alt_deg, pier_side, pixel_scale, exposure_ms, sample_count, cadence_s, span_s, cycles, drift_arcsec_min, period_s, period_sigma_s, period_fixed, harmonics_json, amp1_arcsec, phase1_deg, periodic_rms, residual_rms, peak_to_peak, guiding_active, pec_on, ra_sign, options_json, warnings_json, tool_version, notes FROM runs ORDER BY created_at DESC, id DESC LIMIT ?
`

func (q *Queries) ListRuns(ctx context.Context, limit int64) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Kind,
			&i.FileSha256,
			&i.SourceName,
			&i.SessionIndex,
			&i.SessionBegins,
			&i.Equipment,
			&i.RaHours,
			&i.DecDeg,
			&i.HourAngle,
			&i.AltDeg,
			&i.PierSide,
			&i.PixelScale,
			&i.ExposureMs,
			&i.SampleCount,
			&i.CadenceS,
			&i.SpanS,
			&i.Cycles,
			&i.DriftArcsecMin,
			&i.PeriodS,
			&i.PeriodSigmaS,
			&i.PeriodFixed,
			&i.HarmonicsJson,
			&i.Amp1Arcsec,
			&i.Phase1Deg,
			&i.PeriodicRms,
			&i.ResidualRms,
			&i.PeakToPeak,
			&i.GuidingActive,
			&i.PecOn,
			&i.RaSign,
			&i.OptionsJson,
			&i.WarningsJson,
			&i.ToolVersion,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTableRuns = `-- name: ListTableRuns :many
SELECT id, created_at, kind, file_sha256, source_name, session_index, session_begins, equipment, ra_hours, dec_deg, hour_angle, alt_deg, pier_side, pixel_scale, exposure_ms, sample_count, cadence_s, span_s, cycles, drift_arcsec_min, period_s, period_sigma_s, period_fixed, harmonics_json, amp1_arcsec, phase1_deg, periodic_rms, residual_rms, peak_to_peak, guiding_active, pec_on, ra_sign, options_json, warnings_json, tool_version, notes FROM runs WHERE kind = 'table' ORDER BY created_at DESC, id DESC LIMIT ?
`

func (q *Queries) ListTableRuns(ctx context.Context, limit int64) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listTableRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Kind,
			&i.FileSha256,
			&i.SourceName,
			&i.SessionIndex,
			&i.SessionBegins,
			&i.Equipment,
			&i.RaHours,
			&i.DecDeg,
			&i.HourAngle,
			&i.AltDeg,
			&i.PierSide,
			&i.PixelScale,
			&i.ExposureMs,
			&i.SampleCount,
			&i.CadenceS,
			&i.SpanS,
			&i.Cycles,
			&i.DriftArcsecMin,
			&i.PeriodS,
			&i.PeriodSigmaS,
			&i.PeriodFixed,
			&i.HarmonicsJson,
			&i.Amp1Arcsec,
			&i.Phase1Deg,
			&i.PeriodicRms,
			&i.ResidualRms,
			&i.PeakToPeak,
			&i.GuidingActive,
			&i.PecOn,
			&i.RaSign,
			&i.OptionsJson,
			&i.WarningsJson,
			&i.ToolVersion,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnsavedLiveFiles = `-- name: ListUnsavedLiveFiles :many
SELECT sha256, kind, name, size, uploaded_at FROM files f
WHERE f.kind = 'phd2live'
  AND NOT EXISTS (SELECT 1 FROM runs r WHERE r.file_sha256 = f.sha256)
ORDER BY f.uploaded_at DESC, f.sha256
LIMIT ?
`

func (q *Queries) ListUnsavedLiveFiles(ctx context.Context, limit int64) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listUnsavedLiveFiles, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.Sha256,
			&i.Kind,
			&i.Name,
			&i.Size,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSetting = `-- name: SetSetting :exec
INSERT INTO settings (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) error {
	_, err := q.db.ExecContext(ctx, setSetting, arg.Key, arg.Value)
	return err
}

const updateFitNotes = `-- name: UpdateFitNotes :exec
UPDATE fits SET notes = ? WHERE id = ?
`

type UpdateFitNotesParams struct {
	Notes string `json:"notes"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateFitNotes(ctx context.Context, arg UpdateFitNotesParams) error {
	_, err := q.db.ExecContext(ctx, updateFitNotes, arg.Notes, arg.ID)
	return err
}

const updateRunNotes = `-- name: UpdateRunNotes :exec
UPDATE runs SET notes = ?, pec_on = ? WHERE id = ?
`

type UpdateRunNotesParams struct {
	Notes string        `json:"notes"`
	PecOn sql.NullInt64 `json:"pec_on"`
	ID    int64         `json:"id"`
}

func (q *Queries) UpdateRunNotes(ctx context.Context, arg UpdateRunNotesParams) error {
	_, err := q.db.ExecContext(ctx, updateRunNotes, arg.Notes, arg.PecOn, arg.ID)
	return err
}

const upsertFile = `-- name: UpsertFile :exec
INSERT INTO files (sha256, kind, name, size, uploaded_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(sha256) DO UPDATE SET name = excluded.name
`

type UpsertFileParams struct {
	Sha256     string `json:"sha256"`
	Kind       string `json:"kind"`
	Name       string `json:"name"`
	Size       int64  `json:"size"`
	UploadedAt string `json:"uploaded_at"`
}

func (q *Queries) UpsertFile(ctx context.Context, arg UpsertFileParams) error {
	_, err := q.db.ExecContext(ctx, upsertFile,
		arg.Sha256,
		arg.Kind,
		arg.Name,
		arg.Size,
		arg.UploadedAt,
	)
	return err
}
