// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const deleteRun = `-- name: DeleteRun :exec
DELETE FROM runs WHERE id = ?
`

func (q *Queries) DeleteRun(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRun, id)
	return err
}

const getFile = `-- name: GetFile :one
SELECT sha256, kind, name, size, uploaded_at FROM files WHERE sha256 = ?
`

func (q *Queries) GetFile(ctx context.Context, sha256 string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFile, sha256)
	var i File
	err := row.Scan(
		&i.Sha256,
		&i.Kind,
		&i.Name,
		&i.Size,
		&i.UploadedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, created_at, kind, file_sha256, source_name, session_index, session_begins, equipment, ra_hours, dec_deg, hour_angle, alt_deg, pier_side, pixel_scale, exposure_ms, sample_count, cadence_s, span_s, cycles, drift_arcsec_min, period_s, period_sigma_s, period_fixed, harmonics_json, amp1_arcsec, phase1_deg, periodic_rms, residual_rms, peak_to_peak, guiding_active, pec_on, ra_sign, options_json, warnings_json, tool_version, notes FROM runs WHERE id = ?
`

func (q *Queries) GetRun(ctx context.Context, id int64) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Kind,
		&i.FileSha256,
		&i.SourceName,
		&i.SessionIndex,
		&i.SessionBegins,
		&i.Equipment,
		&i.RaHours,
		&i.DecDeg,
		&i.HourAngle,
		&i.AltDeg,
		&i.PierSide,
		&i.PixelScale,
		&i.ExposureMs,
		&i.SampleCount,
		&i.CadenceS,
		&i.SpanS,
		&i.Cycles,
		&i.DriftArcsecMin,
		&i.PeriodS,
		&i.PeriodSigmaS,
		&i.PeriodFixed,
		&i.HarmonicsJson,
		&i.Amp1Arcsec,
		&i.Phase1Deg,
		&i.PeriodicRms,
		&i.ResidualRms,
		&i.PeakToPeak,
		&i.GuidingActive,
		&i.PecOn,
		&i.RaSign,
		&i.OptionsJson,
		&i.WarningsJson,
		&i.ToolVersion,
		&i.Notes,
	)
	return i, err
}

const insertRun = `-- name: InsertRun :execresult
INSERT INTO runs (
    created_at, kind, file_sha256, source_name, session_index, session_begins, equipment,
    ra_hours, dec_deg, hour_angle, alt_deg, pier_side, pixel_scale, exposure_ms,
    sample_count, cadence_s, span_s, cycles, drift_arcsec_min,
    period_s, period_sigma_s, period_fixed, harmonics_json, amp1_arcsec, phase1_deg,
    periodic_rms, residual_rms, peak_to_peak, guiding_active, pec_on, ra_sign,
    options_json, warnings_json, tool_version, notes
) VALUES (
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?
)
`

type InsertRunParams struct {
	CreatedAt      string        `json:"created_at"`
	Kind           string        `json:"kind"`
	FileSha256     string        `json:"file_sha256"`
	SourceName     string        `json:"source_name"`
	SessionIndex   int64         `json:"session_index"`
	SessionBegins  string        `json:"session_begins"`
	Equipment      string        `json:"equipment"`
	RaHours        float64       `json:"ra_hours"`
	DecDeg         float64       `json:"dec_deg"`
	HourAngle      float64       `json:"hour_angle"`
	AltDeg         float64       `json:"alt_deg"`
	PierSide       string        `json:"pier_side"`
	PixelScale     float64       `json:"pixel_scale"`
	ExposureMs     int64         `json:"exposure_ms"`
	SampleCount    int64         `json:"sample_count"`
	CadenceS       float64       `json:"cadence_s"`
	SpanS          float64       `json:"span_s"`
	Cycles         float64       `json:"cycles"`
	DriftArcsecMin float64       `json:"drift_arcsec_min"`
	PeriodS        float64       `json:"period_s"`
	PeriodSigmaS   float64       `json:"period_sigma_s"`
	PeriodFixed    int64         `json:"period_fixed"`
	HarmonicsJson  string        `json:"harmonics_json"`
	Amp1Arcsec     float64       `json:"amp1_arcsec"`
	Phase1Deg      float64       `json:"phase1_deg"`
	PeriodicRms    float64       `json:"periodic_rms"`
	ResidualRms    float64       `json:"residual_rms"`
	PeakToPeak     float64       `json:"peak_to_peak"`
	GuidingActive  int64         `json:"guiding_active"`
	PecOn          sql.NullInt64 `json:"pec_on"`
	RaSign         float64       `json:"ra_sign"`
	OptionsJson    string        `json:"options_json"`
	WarningsJson   string        `json:"warnings_json"`
	ToolVersion    string        `json:"tool_version"`
	Notes          string        `json:"notes"`
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertRun,
		arg.CreatedAt,
		arg.Kind,
		arg.FileSha256,
		arg.SourceName,
		arg.SessionIndex,
		arg.SessionBegins,
		arg.Equipment,
		arg.RaHours,
		arg.DecDeg,
		arg.HourAngle,
		arg.AltDeg,
		arg.PierSide,
		arg.PixelScale,
		arg.ExposureMs,
		arg.SampleCount,
		arg.CadenceS,
		arg.SpanS,
		arg.Cycles,
		arg.DriftArcsecMin,
		arg.PeriodS,
		arg.PeriodSigmaS,
		arg.PeriodFixed,
		arg.HarmonicsJson,
		arg.Amp1Arcsec,
		arg.Phase1Deg,
		arg.PeriodicRms,
		arg.ResidualRms,
		arg.PeakToPeak,
		arg.GuidingActive,
		arg.PecOn,
		arg.RaSign,
		arg.OptionsJson,
		arg.WarningsJson,
		arg.ToolVersion,
		arg.Notes,
	)
}

const listAnalyseRuns = `-- name: ListAnalyseRuns :many
SELECT id, created_at, kind, file_sha256, source_name, session_index, session_begins, equipment, ra_hours, dec_deg, hour_angle, alt_deg, pier_side, pixel_scale, exposure_ms, sample_count, cadence_s, span_s, cycles, drift_arcsec_min, period_s, period_sigma_s, period_fixed, harmonics_json, amp1_arcsec, phase1_deg, periodic_rms, residual_rms, peak_to_peak, guiding_active, pec_on, ra_sign, options_json, warnings_json, tool_version, notes FROM runs WHERE kind = 'analyse' ORDER BY created_at DESC, id DESC LIMIT ?
`

func (q *Queries) ListAnalyseRuns(ctx context.Context, limit int64) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listAnalyseRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Kind,
			&i.FileSha256,
			&i.SourceName,
			&i.SessionIndex,
			&i.SessionBegins,
			&i.Equipment,
			&i.RaHours,
			&i.DecDeg,
			&i.HourAngle,
			&i.AltDeg,
			&i.PierSide,
			&i.PixelScale,
			&i.ExposureMs,
			&i.SampleCount,
			&i.CadenceS,
			&i.SpanS,
			&i.Cycles,
			&i.DriftArcsecMin,
			&i.PeriodS,
			&i.PeriodSigmaS,
			&i.PeriodFixed,
			&i.HarmonicsJson,
			&i.Amp1Arcsec,
			&i.Phase1Deg,
			&i.PeriodicRms,
			&i.ResidualRms,
			&i.PeakToPeak,
			&i.GuidingActive,
			&i.PecOn,
			&i.RaSign,
			&i.OptionsJson,
			&i.WarningsJson,
			&i.ToolVersion,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, created_at, kind, file_sha256, source_name, session_index, session_begins, equipment, ra_hours, dec_deg, hour_angle, alt_deg, pier_side, pixel_scale, exposure_ms, sample_count, cadence_s, span_s, cycles, drift_arcsec_min, period_s, period_sigma_s, period_fixed, harmonics_json, amp1_arcsec, phase1_deg, periodic_rms, residual_rms, peak_to_peak, guiding_active, pec_on, ra_sign, options_json, warnings_json, tool_version, notes FROM runs ORDER BY created_at DESC, id DESC LIMIT ?
`

func (q *Queries) ListRuns(ctx context.Context, limit int64) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Kind,
			&i.FileSha256,
			&i.SourceName,
			&i.SessionIndex,
			&i.SessionBegins,
			&i.Equipment,
			&i.RaHours,
			&i.DecDeg,
			&i.HourAngle,
			&i.AltDeg,
			&i.PierSide,
			&i.PixelScale,
			&i.ExposureMs,
			&i.SampleCount,
			&i.CadenceS,
			&i.SpanS,
			&i.Cycles,
			&i.DriftArcsecMin,
			&i.PeriodS,
			&i.PeriodSigmaS,
			&i.PeriodFixed,
			&i.HarmonicsJson,
			&i.Amp1Arcsec,
			&i.Phase1Deg,
			&i.PeriodicRms,
			&i.ResidualRms,
			&i.PeakToPeak,
			&i.GuidingActive,
			&i.PecOn,
			&i.RaSign,
			&i.OptionsJson,
			&i.WarningsJson,
			&i.ToolVersion,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunNotes = `-- name: UpdateRunNotes :exec
UPDATE runs SET notes = ?, pec_on = ? WHERE id = ?
`

type UpdateRunNotesParams struct {
	Notes string        `json:"notes"`
	PecOn sql.NullInt64 `json:"pec_on"`
	ID    int64         `json:"id"`
}

func (q *Queries) UpdateRunNotes(ctx context.Context, arg UpdateRunNotesParams) error {
	_, err := q.db.ExecContext(ctx, updateRunNotes, arg.Notes, arg.PecOn, arg.ID)
	return err
}

const upsertFile = `-- name: UpsertFile :exec
INSERT INTO files (sha256, kind, name, size, uploaded_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(sha256) DO UPDATE SET name = excluded.name
`

type UpsertFileParams struct {
	Sha256     string `json:"sha256"`
	Kind       string `json:"kind"`
	Name       string `json:"name"`
	Size       int64  `json:"size"`
	UploadedAt string `json:"uploaded_at"`
}

func (q *Queries) UpsertFile(ctx context.Context, arg UpsertFileParams) error {
	_, err := q.db.ExecContext(ctx, upsertFile,
		arg.Sha256,
		arg.Kind,
		arg.Name,
		arg.Size,
		arg.UploadedAt,
	)
	return err
}
